### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by x64bugreport** [EVA-JianJun/Mconfig#1]
1.可否去掉默认生成配置文件中的默认填充字段
2.希望增加一个纯配置作用域，而不是与类绑定
3.以下调用不成功
    def __init__(self, account, pwdhash):
        self.userinfo = type("aaaa", (object,), {'userinfo': None})
        self.kxconfig = Mconfig(self.configname)
        self.kxconfig.aaaa.num = 1
我希望动态生成配置字段名，作用域名称。

class A:
    class aaaa:
        userinfo = None

    def __init__(self, account, pwdhash):
        self.kxconfig = Mconfig(self.configname)
        self.kxconfig.aaaa.num = 1

以上也失败。。。。找不到类

**Comment by EVA-JianJun** [comment]
**先更新到1.1.5**
`pip install Mconfig==1.1.5`
我刚上传的, 你如果用pip源可能没更新, 用官方源就行.

1.如果设置的文件名不为 `mconfig.py` 则会创建空文件
2.每一个类就是一个单独的作用域, 简洁明了, 看下面演示代码

```
import Mconfig

# 创建空配置文件
mc = Mconfig("config.py")

# 不支持 None, 用空字符代替吧
# 你要用type就这样写
tom = type('Tom', (object,), {'userinfo': 'cat', 'username': 'Tom'})
jerry = type('Jerry', (object,), {'userinfo': 'mouse', 'username': 'Jerry'})
addr_info = type('AddrInfo', (object,), {'addr': 'something', 'addr_id': 10})

# 也可以 class 一样的
# class tom():
#     userinfo = 'cat'
#     username = 'Tom'

mc.Tom = tom
mc.Jerry = jerry
mc.AddrInfo = addr_info

print(mc.Tom.userinfo)
print(mc.Jerry.username)
```

** 这不是数据库, 这是配置文件, 如果配置文件过大没测试过, 因为我看你写了 `userinfo`, 如果你有几万个用户信息存在这个配置文件中我不到性能怎么样或者会不会出其他问题. **

**Comment by EVA-JianJun** [comment]
如果有其他问题再给我留言
