### ISSUE TITLE
打包运行后报错

### ISSUE THREAD

**Issue by zhubochao** [EVA-JianJun/Mconfig#2]
![image](https://github.com/user-attachments/assets/673712a1-ff20-4935-b069-175128df69e2)

**Comment by EVA-JianJun** [comment]
这个项目是我早期突发奇想写的项目, 虽然正常情况下可以正常使用, 但是确实会遇到你这样的问题, 且我这种方式的配置文件也有他的问题和局限性, 所以不推荐在生产环境中使用, 推荐使用 yaml, TOML 等更现代的配置文件, 或者 json 等传统的配置文件.

This project is a project I wrote on a whim in the early days, although under normal circumstances it can be used normally, but it does encounter problems such as yours, and my way of configuring files also has its own problems and limitations, so it is not recommended to use in production environments, and it is recommended to use yaml, TOML and other more modern configuration files, or json and other traditional configuration files.

**Comment by EVA-JianJun** [comment]
@zhubochao
